### ISSUE TITLE
.dmg builds and releases are actually Mach-O executables

### ISSUE THREAD

**Issue by kernel-sanders** [Ne0nd0g/merlin#26]
Just a note to let you know that the "dmg" releases and builds from source for Darwin are actually Mach-O executables. Unless this was purposeful obfuscation for some reason, in which case... carry on.

```bash
$ file /.../merlinAgent-Darwin-x64-v0.6.0/merlinAgent-Darwin-x64.dmg
/.../merlinAgent-Darwin-x64-v0.6.0/merlinAgent-Darwin-x64.dmg: Mach-O 64-bit executable x86_64
```

**Comment by Ne0nd0g** [comment]
Thanks for the heads @kernel-sanders , it wasn't an attempt for purposeful obfuscation. My goal was to have a file extension on it so that I could easily sort it among other binary files. I'm not super familiar with MacOS and found that with a `dmg` extension I could meet my goal and the file would execute fine on the CLI. Is there a better extension I should use? Maybe just `.bundle`?

**Comment by kernel-sanders** [comment]
I would suggest `.bin` or `.macho` just to prevent people (like me) from trying to extract the disk image and failing.
