### ISSUE TITLE
Issue with the Invoke-Merlin.ps1 script

### ISSUE THREAD

**Issue by edify42** [Ne0nd0g/merlin#42]
### Prerequisite
* [*] I have read the [README](https://github.com/Ne0nd0g/merlin/blob/master/README.MD)
* [*] I have search the opened & _closed_ [issues](https://github.com/Ne0nd0g/merlin/issues)
* [*] I have search the [WIKI](https://github.com/Ne0nd0g/merlin/wiki) and its [FAQ](https://github.com/Ne0nd0g/merlin/wiki/FAQ) page
### Environment Data
* Merlin Version: 0.6.0
* Merlin Build: N/A
* Go Version: go1.11.2 darwin/amd64
* GOPATH Environment Variable: $HOME/Development/misc-apps
* GOROOT Environment Variable: nil
* Operating System: MacOS Darwin Kernel Version 18.2.0

### Expected Behavior

No complaints from AntiVirus definitions engine

### Actual Behavior

Hacktool.Mimikatz detected in the Invoke-Merlin.ps1 script

### Steps to Reproduce Behavior

Bit hard, we have a custom Symantec AV engine.

### Misc Information

**Comment by Ne0nd0g** [comment]
@edify42 I'm not sure I understand the issue with Merlin. Are reporting that you expected `Invoke-Merlin.ps1` to bypass AV and because it didn't, there is an issue? If just want to chat about it, consider joining the Slack channel using the badge on he README. Alternatively, join the #merlin channel in the BloodHoundGang slack (open signups).

Invoke-merlin.ps1 is largely based off PowerSploit's `Invoke-ReflectivePEInjection` that loads and executes a DLL. `Invoke-Mimikatz` also uses this setup to run the Mimikatz DLL and is likely the reason your AV reported that signature for Invoke-Merlin. Your options are to identify a bypass or to disable AV before executing the script. You might have better luck executing the `merlin.dll` with `rundll32.exe`

**Comment by edify42** [comment]
All good, I wanted confirmation from you that it's known functionality. I'll ignore the AV warning.
